version: 2

models:
  - name: Skin_Disease_Picture
    config:
      contract:
        enforced: true
    columns:
      - name: picture_id
        data_type: integer
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: disease_name
        data_type: string
      - name: affected_skin_color
        data_type: string
      - name: severity
        data_type: string
      - name: image_link
        data_type: string
        